
language: julia
julia:
  - 1.3
  - 1.3.1

env:
  matrix:
    - JULIA_NUM_THREADS=4

after_success:
  - julia --project -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
