
name: Julia Testing
on:
  push:
    branches: [ master, construction ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        julia-version: ['1.3']

    steps:
    - uses: actions/checkout@v1.0.0
    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    # - name: Build Package
      # uses: julia-actions/julia-buildpkg@latest
    - name: Test Package
      run: |
        julia --project=@. -e "using Pkg; Pkg.instantiate();"
        julia --project=@. -e "using Pkg; Pkg.test(\"test\");"

    - name: Upload coverage to Codecov
      uses: julia-actions/julia-uploadcodecov@latest